// Checks the support desk without sending real email. Run: node test/support.test.js
const http = require('http'), fs = require('fs'), os = require('os'), path = require('path');
const { createApp } = require('../app');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'hearth-support-'));
const sent = []; const transport = { sendMail: async (m) => { sent.push(m); } };
const app = createApp({ dataDir: dir, transport, from: 'hearth.support1@gmail.com', owners: ['me@example.com'], resolveMx: async (d) => d !== 'nope.invalid' });
const srv = http.createServer((q, r) => app.handle(q, r));
let pass = 0, fail = 0; const ok = (n, c, x = '') => { c ? pass++ : fail++; console.log((c ? 'PASS ' : 'FAIL ') + n + (x ? '  ' + x : '')); };
const call = (method, p, tok, body) => new Promise((res) => { const d = body ? Buffer.from(JSON.stringify(body)) : null; const r = http.request({ host: '127.0.0.1', port: srv.address().port, path: p, method, headers: { ...(tok ? { Authorization: 'Bearer ' + tok } : {}), ...(d ? { 'Content-Type': 'application/json', 'Content-Length': d.length } : {}) } }, (rs) => { let b = ''; rs.on('data', (x) => { b += x; }); rs.on('end', () => res({ code: rs.statusCode, j: JSON.parse(b || '{}') })); }); r.end(d || undefined); });
const lastTo = (to) => [...sent].reverse().find((m) => m.to === to);
srv.listen(0, '127.0.0.1', async () => {
  ok('1 bad address refused', (await call('POST', '/auth/start', null, { email: 'not an email' })).code === 400);
  ok('2 unknown domain refused', (await call('POST', '/auth/start', null, { email: 'a@nope.invalid' })).code === 400);
  const s = await call('POST', '/auth/start', null, { email: 'Kid@Example.com' });
  const m1 = lastTo('kid@example.com'); const code = (/(\d{3}) (\d{3})/.exec(m1.subject) || []).slice(1).join('');
  ok('3 a code is emailed with a nice layout', s.code === 200 && code.length === 6 && m1.html.includes('#F0643C') && m1.html.includes('hearth-mail.png') && m1.text.includes(code.slice(0, 3) + ' ' + code.slice(3)));
  ok('4 wrong code refused', (await call('POST', '/auth/verify', null, { email: 'kid@example.com', code: '000000' })).code === 400);
  const v = await call('POST', '/auth/verify', null, { email: 'kid@example.com', code });
  ok('5 right code signs in', v.code === 200 && v.j.token && v.j.token.length === 64);
  const tok = v.j.token;
  ok('6 requests need a sign-in', (await call('GET', '/tickets', null)).code === 401);
  ok('7 too short a request is refused', (await call('POST', '/tickets', tok, { category: 'bug', title: 'x', text: 'short' })).code === 400);
  sent.length = 0;
  const t = await call('POST', '/tickets', tok, { category: 'bug', title: 'App closes <b>on start</b>', text: 'When I open it, it closes.\n<script>alert(1)</script>', meta: { app: 'Phone', version: '1.0.2', platform: 'Android 15' } });
  ok('8 a request is created', t.code === 200 && /^HRT-\d{5}$/.test(t.j.id) && t.j.mailed === true);
  const conf = lastTo('kid@example.com'), note = lastTo('hearth.support1@gmail.com');
  ok('9 the person gets a confirmation with the number', conf && conf.subject.includes(t.j.id) && conf.html.includes('What happens next') && conf.replyTo.includes('+' + t.j.id));
  ok('10 you get the request, reply goes through the desk', note && note.subject.startsWith('[' + t.j.id + '] Bug:') && note.html.includes('Android 15') && note.replyTo === 'hearth.support1+' + t.j.id + '@gmail.com');
  ok('11 user text is escaped in every email', !conf.html.includes('<script>') && !note.html.includes('<script>') && note.html.includes('&lt;script&gt;'));
  ok('12 they can list and open their request', (await call('GET', '/tickets', tok)).j.length === 1 && (await call('GET', '/tickets/' + t.j.id, tok)).j.messages.length === 1);
  const other = (await (async () => { await call('POST', '/auth/start', null, { email: 'other@example.com' }); const c2 = (/(\d{3}) (\d{3})/.exec(lastTo('other@example.com').subject)).slice(1).join(''); return call('POST', '/auth/verify', null, { email: 'other@example.com', code: c2 }); })()).j.token;
  ok('13 nobody else can open it', (await call('GET', '/tickets/' + t.j.id, other)).code === 404);
  sent.length = 0;
  await call('POST', '/tickets/' + t.j.id + '/messages', tok, { text: 'It also happens after a restart.' });
  ok('14 a follow-up in the app reaches you', lastTo('hearth.support1@gmail.com').subject.includes('new message'));
  sent.length = 0;
  const r = await app.inbound({ from: 'hearth.support1@gmail.com', to: ['hearth.support1+' + t.j.id + '@gmail.com'], subject: 'Re: x', text: 'Please update to 1.0.3.\n\nOn Tue, Hearth wrote:\n> old text', authOk: true });
  const rep = lastTo('kid@example.com');
  ok('15 your emailed reply is sent to them with the layout, quote removed', r.handled && rep && rep.html.includes('Please update to 1.0.3') && !rep.html.includes('old text') && rep.subject.startsWith('Re: [' + t.j.id + ']'));
  ok('16 and shows in their request', (await call('GET', '/tickets/' + t.j.id, tok)).j.messages.slice(-1)[0].from === 'support');
  ok('17 a forged reply is ignored', (await app.inbound({ from: 'hearth.support1@gmail.com', to: [], subject: '[' + t.j.id + ']', text: 'send money', authOk: false })).handled === false);
  ok('18 a stranger cannot answer', (await app.inbound({ from: 'evil@example.com', to: [], subject: '[' + t.j.id + ']', text: 'hi', authOk: true })).handled === false);
  sent.length = 0;
  ok('19 the person can answer by email', (await app.inbound({ from: 'kid@example.com', to: [], subject: 'Re: [' + t.j.id + ']', text: 'Thanks, it works now.', authOk: false })).kind === 'follow-up' && lastTo('hearth.support1@gmail.com'));
  let last; for (let i = 0; i < 6; i++) last = await call('POST', '/tickets', tok, { category: 'idea', title: 'Idea ' + i, text: 'A long enough idea text.' });
  ok('20 too many requests in a day are refused', last.code === 429);
  ok('21 a failed email is queued, not lost', await (async () => { const a = createApp({ dataDir: fs.mkdtempSync(path.join(os.tmpdir(), 'hs3-')), transport: { sendMail: async () => { throw new Error('smtp down'); } }, from: 'a@b.co', resolveMx: async () => true }); const res = await new Promise((rs) => { const s2 = http.createServer((q2, r2) => a.handle(q2, r2)).listen(0, async () => { const port = s2.address().port; const rq = (b) => new Promise((x) => { const d = Buffer.from(JSON.stringify(b)); const h = http.request({ host: '127.0.0.1', port, path: '/auth/start', method: 'POST', headers: { 'Content-Type': 'application/json', 'Content-Length': d.length } }, (rr) => { rr.resume(); x(rr.statusCode); }); h.end(d); }); const code = await rq({ email: 'x@y.com' }); s2.close(); rs(code); }); }); return res === 502 && a.db().outbox.length === 1; })());
  srv.close(); fs.rmSync(dir, { recursive: true, force: true });
  console.log(`\n${pass} passed, ${fail} failed`); process.exit(fail ? 1 : 0);
});
